services:
  - type: web
    name: jay-codez-obfuscator
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: "10000"